# https://github.com/jesseduffield/lazygit/blob/master/docs/Config.md
gui:
  border: rounded
  enlargedSideViewLocation: 'top'
  expandFocusedSidePanel: true
  filterMode: 'fuzzy'
  nerdFontsVersion: '3'
  showBottomLine: true
  showCommandLog: true
  showDivergenceFromBaseBranch: arrowAndNumber
  showFileTree: true
  skipRewordInEditorWarning: true
  theme:
    activeBorderColor:
      - '#a6d189'
      - bold
    inactiveBorderColor:
      - '#737994'
    searchingActiveBorderColor:
      - '#8caaee'
      - bold
    optionsTextColor:
      - '#8caaee'
    selectedLineBgColor:
      - '#292c3c'
      - bold
    cherryPickedCommitBgColor:
      - bold
    cherryPickedCommitFgColor:
      - '#8caaee'
    defaultFgColor:
      - default
git:
  autoFetch: false
  autoForwardBranches: none
  paging:
    colorArg: always
    pager: delta --dark --side-by-side --paging=never --tabs=2
  parseEmoji: true
notARepository: 'quit'
promptToReturnFromSubprocess: false
